# general
seed: 1
device: 'cuda'
output_path: 'pnp_cond_image_feature_extract/wt'

# data
image_path: 'data/wt.jpg'
latents_path: 'pnp_cond_image_latents'

# diffusion
sd_version: '1.5'
guidance_scale: 7.5
n_timesteps: 50
prompt: a photo of a mechanical war horse runs wildly through the universe
negative_prompt: ugly, blurry, black, low res, unrealistic

# pnp injection thresholds, ∈ [0, 1]
pnp_attn_t: 0.5
pnp_f_t: 0.8
